
'use server';
/**
 * @fileOverview A simple AI chatbot flow for HealthFirst Connect.
 *
 * - `chatWithBot` - A function that handles a user's message and returns the bot's response.
 * - `ChatInput` - The input type for the `chatWithBot` function.
 * - `ChatOutput` - The return type for the `chatWithBot` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ChatInputSchema = z.object({
  userInput: z.string().describe('The message sent by the user to the chatbot.'),
});
export type ChatInput = z.infer<typeof ChatInputSchema>;

const ChatOutputSchema = z.object({
  botResponse: z.string().describe('The response generated by the chatbot.'),
});
export type ChatOutput = z.infer<typeof ChatOutputSchema>;

export async function chatWithBot(input: ChatInput): Promise<ChatOutput> {
  return chatFlow(input);
}

const prompt = ai.definePrompt({
  name: 'chatFlowPrompt',
  input: {schema: ChatInputSchema},
  output: {schema: ChatOutputSchema},
  prompt: `You are "MediBuddy", a friendly and helpful AI assistant for HealthFirst Connect, a modern medical clinic.
Your goal is to assist users with information about our services, help them understand how to book appointments, answer general questions about our clinic, and provide general, commonly-known wellness tips that are NOT specific medical advice.

You can talk about:
- Our available services (General Consultation, Cardiology, Physiotherapy, Dermatology, Ophthalmology, Pediatrics). You can find details about these services in the app.
- How to book an appointment using the online form.
- General information about HealthFirst Connect. For example, the app's name is HealthFirst Connect.
- General wellness topics and commonly known, non-prescriptive tips for minor, non-urgent issues (e.g., "for a common cold, it's generally advised to get plenty of rest and stay hydrated," or "for a minor headache, ensure you're hydrated and consider resting in a quiet, dark room.").

IMPORTANT:
- You MUST NOT provide any specific medical advice, diagnosis, or treatment suggestions for individual conditions. Your wellness tips should be very general, widely accepted, and not personalized.
- If a user asks for specific medical advice, describes symptoms that could be serious, or asks for a diagnosis, you MUST politely decline and strongly suggest they book an appointment with one of our qualified doctors or seek urgent medical attention if appropriate. For example, say: "While I can share some general wellness information, I'm not qualified to give specific medical advice for your situation. It's best to book an appointment with a doctor who can help." or "For serious concerns, please seek medical attention promptly."
- If you don't know the answer to something, say "I'm sorry, I don't have information on that, but you can try contacting our support or booking an appointment."
- Keep your responses concise and easy to understand.
- Be empathetic and patient.

User's question: {{{userInput}}}
Answer as MediBuddy.`,
});

const chatFlow = ai.defineFlow(
  {
    name: 'chatFlow',
    inputSchema: ChatInputSchema,
    outputSchema: ChatOutputSchema,
    config: { // Added safety settings to be less restrictive on "dangerous content" which might be triggered by health discussions
      safetySettings: [
        {
          category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
          threshold: 'BLOCK_MEDIUM_AND_ABOVE', // Was implicitly BLOCK_LOW_AND_ABOVE or stricter by default
        },
        {
          category: 'HARM_CATEGORY_HATE_SPEECH',
          threshold: 'BLOCK_ONLY_HIGH',
        },
        {
          category: 'HARM_CATEGORY_HARASSMENT',
          threshold: 'BLOCK_MEDIUM_AND_ABOVE',
        },
        {
          category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
          threshold: 'BLOCK_MEDIUM_AND_ABOVE', // Adjusted from BLOCK_LOW if it was too strict
        },
      ],
    }
  },
  async (input: ChatInput) => {
    const {output} = await prompt(input);
    if (!output) {
      // Handle cases where the output might be null or undefined,
      // though with a defined output schema, this is less likely for valid responses.
      return { botResponse: "I'm having a little trouble responding right now. Please try again in a moment." };
    }
    return output;
  }
);

