
'use server';
/**
 * @fileOverview A simple AI chatbot flow for HealthFirst Connect.
 *
 * - `chatWithBot` - A function that handles a user's message and returns the bot's response.
 * - `ChatInput` - The input type for the `chatWithBot` function.
 * - `ChatOutput` - The return type for the `chatWithBot` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ChatInputSchema = z.object({
  userInput: z.string().describe('The message sent by the user to the chatbot.'),
});
export type ChatInput = z.infer<typeof ChatInputSchema>;

const ChatOutputSchema = z.object({
  botResponse: z.string().describe('The response generated by the chatbot.'),
});
export type ChatOutput = z.infer<typeof ChatOutputSchema>;

export async function chatWithBot(input: ChatInput): Promise<ChatOutput> {
  return chatFlow(input);
}

const prompt = ai.definePrompt({
  name: 'chatFlowPrompt',
  input: {schema: ChatInputSchema},
  output: {schema: ChatOutputSchema},
  prompt: `You are "MediBuddy", a friendly and helpful AI assistant for HealthFirst Connect, a modern medical clinic.
Your goal is to assist users with information about our services, help them understand how to book appointments, and answer general questions about our clinic.
You can talk about:
- Our available services (General Consultation, Cardiology, Physiotherapy, Dermatology, Ophthalmology, Pediatrics). You can find details about these services in the app.
- How to book an appointment using the online form.
- General information about HealthFirst Connect. For example, the app's name is HealthFirst Connect.

IMPORTANT:
- You MUST NOT provide any medical advice, diagnosis, or treatment suggestions. If a user asks for medical advice, politely decline and suggest they book an appointment with one of our qualified doctors. For example, say: "I'm not qualified to give medical advice, but I can help you book an appointment with a doctor who can."
- If you don't know the answer to something, say "I'm sorry, I don't have information on that, but you can try contacting our support or booking an appointment."
- Keep your responses concise and easy to understand.
- Be empathetic and patient.

User's question: {{{userInput}}}
Answer as MediBuddy.`,
});

const chatFlow = ai.defineFlow(
  {
    name: 'chatFlow',
    inputSchema: ChatInputSchema,
    outputSchema: ChatOutputSchema,
  },
  async (input: ChatInput) => {
    const {output} = await prompt(input);
    if (!output) {
      // Handle cases where the output might be null or undefined,
      // though with a defined output schema, this is less likely for valid responses.
      return { botResponse: "I'm having a little trouble responding right now. Please try again in a moment." };
    }
    return output;
  }
);
